### find all cars
GET http://localhost:8080/cars

### find one car
GET http://localhost:8080/cars/15

### find bodyType | sedan
GET http://localhost:8080/cars/bodyType/sedan

### find bodyType | coupe
GET http://localhost:8080/cars/bodyType/coupe

### find transmissionType | manual
GET http://localhost:8080/cars/transmissionType/manual

### find transmissionType | automatic
GET http://localhost:8080/cars/transmissionType/automatic

### find fuelType | gasoline
GET http://localhost:8080/cars/fuelType/gasoline

### find fuelType | diesel
GET http://localhost:8080/cars/fuelType/diesel

### create new car | VW Golf
POST http://localhost:8080/cars
Content-Type: application/json

{
  "bodyType": "hatchback",
  "brand": "Volkswagen",
  "model": "Golf",
  "generation": "Mk7",
  "price": 18000.0,
  "productionYear": 2014,
  "fuelType": "petrol",
  "mileage": 50000,
  "transmissionType": "manual"

}

### create new car | Toyota RAV4
POST http://localhost:8080/cars
Content-Type: application/json

{
  "bodyType": "SUV",
  "brand": "Toyota",
  "model": "RAV4",
  "generation": "XA30",
  "price": 12000.0,
  "productionYear": 2007,
  "fuelType": "petrol",
  "mileage": 120000,
  "transmissionType": "automatic"
}

### update car information | Toyota Camry
PUT http://localhost:8080/cars/1
Content-Type: application/json

{
  "bodyType": "sedan",
  "brand": "Toyota",
  "model": "Camry",
  "generation": "XV50",
  "price": 20000.0,
  "productionYear": 2017,
  "fuelType": "diesel",
  "mileage": 150000,
  "transmissionType": "manual"
}

### delete what u need
DELETE http://localhost:8080/cars/1


